name: build_linux
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Build Linux
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ocl-icd-libopencl1 opencl-headers ocl-icd-opencl-dev liboctave-dev
      - name: Update RCS keywords
        shell: bash
        run: |
          printf '\n[filter "rcs-keywords"]\n\tclean  = .git_filters/rcs-keywords.clean\n\tsmudge = .git_filters/rcs-keywords.smudge %f\n' >> .git/config
          rm -rf src/*.c
          git checkout src/*.c
      - name: Get current date
        id: date
        run: echo "RELEASE_VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build mcxlabcl for Octave
        shell: bash
        run: |
          cd src
          make oct
          ldd ../mcxlabcl/mcxcl.mex
      - name: Build binary
        shell: bash
        run: |
          cd src
          make clean
          make static
          ldd bin/mcxcl
      - name: Upload mcxlabcl package
        uses: actions/upload-artifact@v3
        with:
          name: mcxlabcl-linux-x64_64-${{ env.RELEASE_VERSION }}
          path: mcxlabcl
      - name: Prepare mcxcl package
        shell: bash
        run: |
          mv src/bin .
          rm -rf .git mcxlabcl src .git_filters .gitattributes .github .travis.yml deploy
          mkdir -p src/bin
          cd src/bin
          ln -s ../../bin/mcxcl .
          cd ../../
      - name: Upload mcxcl package
        uses: actions/upload-artifact@v3
        with:
          name: mcxcl-linux-x64_64-${{ env.RELEASE_VERSION }}
          path: .
